### ISSUE TITLE
Added to Fisherman

### ISSUE THREAD

**Issue by ghost** [daveyarwood/tomita#2]
Thanks for this theme! I have deprecated my old Wahoo framework and now currently working on [Fisherman](https://github.com/fisherman/fisherman). I have added tomita to the pack!

![jan 22 2016 23 35](https://cloud.githubusercontent.com/assets/8317250/12513350/c5e26e3a-c160-11e5-9e62-999366d964a8.gif)

**Comment by daveyarwood** [comment]
Great, thanks! You're welcome to it. :+1:
