### ISSUE TITLE
How to remove vi indicator

### ISSUE THREAD

**Issue by OlivierCuyp** [daveyarwood/tomita#3]
Hi,

I love your theme, but is there a way to get rid of the vi indicator ?
I want to keep as minimal as possible and I'm not interested by the vi mode ...

Regards,
Olivier

**Comment by daveyarwood** [comment]
Hi Olivier, thanks for the kind words!

Removing [these lines](https://github.com/daveyarwood/tomita/blob/master/fish_prompt.fish#L10-L23) should do the trick.

**Comment by OlivierCuyp** [comment]
Dave, thanks for the tip.
It worked like a charm.
